### ISSUE TITLE
Move repository into DiamondLightSource organisation

### ISSUE THREAD

**Issue by DiamondJoseph** [stan-dot/j20-bluesky#13]
As soon as is reasonable, this repository should be moved into the DiamondLightSource organisation.

This will require a user with permissions to create repositories in the org, which is probably why it was made here in the first place.

**Comment by stan-dot** [comment]
just fork it into the new owner

**Comment by stan-dot** [comment]
https://diamondlightsource.slack.com/archives/C06A18ZPP44/p1713878752984699?thread_ts=1713878390.860499&cid=C06A18ZPP44

**Comment by stan-dot** [comment]
done
