### ISSUE TITLE
List GDA functionalities - base this on SWIFT stuff

### ISSUE THREAD

**Issue by stan-dot** [stan-dot/j20-bluesky#4]
- for each scan write a short description, type of experiment it uses and a list of devices and at the same time filter for plans that are outdated

SWIFT will be nearly fully replicable in j20, therefore a ste of features can be taken from there. also a list of devices is a long task and there should be an issue for each one separately

**Comment by stan-dot** [comment]
agreed to start with `/dls_sw/i20-1/scripts/Luke`

**Comment by stan-dot** [comment]
there's also a hundredish  `/dls_sw/i20-1/scripts/imh`

**Comment by stan-dot** [comment]
the first would be the plan for the  t5 (?) motor x axis continuous movement scan and triggering

**Comment by Relm-Arrowny** [comment]
> the first would be the plan for the t5 (?) motor x axis continuous movement scan and triggering

The motor x is TS X motor with epic PV  "BL20J-OP-PCHRO-01:TS:XFINE"

Requirements:
#10 
- Direct movement of the slit position x.
- Continuous movement of the slit.
- Continuous movement of the slit with a defined  Trajectory.


- Trajectory scan: #11 
A trajectory scan is where during a Trajectory movement the detector is triggered by a TTL signal coming from the Zebra box.

**Comment by stan-dot** [comment]
ok let's start with this one - trying to get it onto the server there
